'use client';
import { useEffect,useState,type FormEvent } from 'react';
import Link from 'next/link';
import { getSupabaseClient } from '@/lib/supabaseClient';
import { authErrorMessage,MIN_PASSWORD_LENGTH,replacePassword } from '@/lib/emailAuth';
export default function PasswordForm({requireCurrent=false}:{requireCurrent?:boolean}){
 const client=getSupabaseClient();const [currentPassword,setCurrentPassword]=useState(''),[ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(false),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[updated,setUpdated]=useState(false);
 useEffect(()=>{let active=true;async function check(){try{const result=await client?.auth.getUser();if(active)setSignedIn(!!result?.data.user&&!result.error);}catch{if(active)setError('Unable to verify this recovery session. Request a new link.');}finally{if(active)setReady(true);}}void check();return()=>{active=false;};},[client]);
 async function submit(event:FormEvent){event.preventDefault();if(!client||busy)return;setBusy(true);setError('');try{const result=await replacePassword(client.auth,password,confirmation,requireCurrent?currentPassword:undefined);setPassword('');setConfirmation('');setCurrentPassword('');if(result.signedOut)window.location.assign('/sign-in?passwordUpdated=1');else{setUpdated(true);setError('Your password was updated, but we could not sign out all sessions. Sign out from your account before signing in again.');}}catch(error){setError(authErrorMessage(error));}finally{setBusy(false);}}
 return <main className="auth-page"><section className="auth-card"><Link href="/" className="brand">TOP1</Link><span className="eyebrow">{requireCurrent?'ACCOUNT SECURITY':'ACCOUNT RECOVERY'}</span><h1>{requireCurrent?'Change your password.':'A fresh start.'}</h1>{!ready?<p role="status">{requireCurrent?'Checking your account…':'Checking your recovery link…'}</p>:!signedIn?<><p>{requireCurrent?'Sign in before changing your password.':'This recovery link is missing or expired. Request a new link and open it in the browser where you requested it.'}</p><Link href="/sign-in" className="primary-button">Back to account access</Link></>:<><p>Choose a new password. After saving it, you’ll sign in again.</p><form className="email-auth-form" onSubmit={event=>void submit(event)}><>{requireCurrent&&<label htmlFor="current-password">Current password<input id="current-password" type="password" autoComplete="current-password" required disabled={busy||updated} value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></label>}<label htmlFor="new-password">New password<input id="new-password" type="password" autoComplete="new-password" required minLength={MIN_PASSWORD_LENGTH} maxLength={128} disabled={busy||updated} value={password} onChange={event=>setPassword(event.target.value)}/></label><label htmlFor="confirm-new-password">Confirm new password<input id="confirm-new-password" type="password" autoComplete="new-password" required minLength={MIN_PASSWORD_LENGTH} maxLength={128} disabled={busy||updated} value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><small>At least {MIN_PASSWORD_LENGTH} characters.</small><button className="primary-button auth-submit" type="submit" disabled={busy||updated}>{busy?'Updating…':'Update password'}</button></></form></>}{error&&<p className="field-error" role="alert">{error}</p>}</section></main>;
}
