import {test} from 'node:test';import assert from 'node:assert/strict';
import type {SupabaseClient} from '@supabase/supabase-js';
import {authCallbackUrl,authErrorMessage,normalizeEmail,validatePassword,submitEmailAuth,resendConfirmation,replacePassword} from './emailAuth';
const fake=(methods:Record<string,unknown>)=>methods as unknown as SupabaseClient['auth'];
const secret='test-password-only-with-enough-characters';
test('email validation trims whitespace, rejects malformed addresses and retains case',()=>{assert.equal(normalizeEmail(' Name@example.com '),'Name@example.com');for(const email of ['','a@','a@b','a b@host.com','a@host\n.com'])assert.throws(()=>normalizeEmail(email));});
test('new passwords match, retain whitespace, and have sensible length limits',()=>{validatePassword(secret,secret);assert.throws(()=>validatePassword('short','short'),/12/);assert.throws(()=>validatePassword(secret,'different'),/match/);assert.throws(()=>validatePassword('a'.repeat(129),'a'.repeat(129)),/128/);});
test('callback destinations stay on the current app for confirmation and recovery',()=>{const url=new URL(authCallbackUrl('https://top1.fit','//evil.invalid'));assert.equal(url.origin,'https://top1.fit');assert.equal(url.searchParams.get('next'),'/');assert.equal(new URL(authCallbackUrl('https://top1.fit','/reset-password')).searchParams.get('next'),'/reset-password');});
test('sign-in uses the supplied password without applying new-password rules',async()=>{let received:unknown;const result=await submitEmailAuth(fake({signInWithPassword:async(args:unknown)=>{received=args;return {error:null};}}),'sign-in',' owner@example.com ','existing-short','', 'https://top1.fit');assert.deepEqual(received,{email:'owner@example.com',password:'existing-short'});assert.equal(result.signedIn,true);});
test('unconfirmed signup never reports a signed-in account',async()=>{let received:any;const result=await submitEmailAuth(fake({signUp:async(args:unknown)=>{received=args;return {data:{session:null},error:null};}}),'sign-up','owner@example.com',secret,secret,'https://top1.fit');assert.equal(result.signedIn,false);assert.equal(received.options.emailRedirectTo,authCallbackUrl('https://top1.fit'));assert.match(result.message,/confirm/);});
test('signup respects a provider session only when actually returned',async()=>{const result=await submitEmailAuth(fake({signUp:async()=>({data:{session:{user:{id:'test'}}},error:null})}),'sign-up','owner@example.com',secret,secret,'https://top1.fit');assert.equal(result.signedIn,true);});
test('forgot-password requests the recovery destination without revealing account existence',async()=>{let received:any;const result=await submitEmailAuth(fake({resetPasswordForEmail:async(email:string,options:unknown)=>{received={email,options};return {error:null};}}),'forgot-password','owner@example.com','','','https://top1.fit');assert.equal(received.options.redirectTo,authCallbackUrl('https://top1.fit','/reset-password'));assert.equal(result.signedIn,false);assert.match(result.message,/If this address/);});
test('confirmation resend does not accidentally send a reset or create another account',async()=>{let args:any;await resendConfirmation(fake({resend:async(a:unknown)=>{args=a;return {error:null};}}),'owner@example.com','https://top1.fit');assert.equal(args.type,'signup');});
test('password replacement only signs out sessions after a successful update',async()=>{let signedOut=false;const result=await replacePassword(fake({updateUser:async()=>({error:null}),signOut:async({scope}:{scope:string})=>{assert.equal(scope,'global');signedOut=true;return {error:null};}}),secret,secret);assert.equal(signedOut,true);assert.equal(result.signedOut,true);signedOut=false;await assert.rejects(replacePassword(fake({updateUser:async()=>({error:new Error('expired')}),signOut:async()=>{signedOut=true;return {error:null};}}),secret,secret));assert.equal(signedOut,false);});
test('auth errors avoid dumping provider internals or credential strings',()=>{assert.equal(authErrorMessage({code:'invalid_credentials'}),'The email or password is incorrect.');assert.match(authErrorMessage({code:'email_not_confirmed'}),/Confirm your email/);const providerError=new Error('secret provider detail');providerError.name='AuthApiError';assert.ok(!authErrorMessage(providerError).includes('secret'));assert.match(authErrorMessage({code:'over_email_send_rate_limit'}),/Too many/);});
test('signed-in password changes verify the current password with the provider',async()=>{let payload:any;await replacePassword(fake({getUser:async()=>({data:{user:{id:'owner',email:'owner@example.com'}},error:null}),signInWithPassword:async()=>({data:{user:{id:'owner'}},error:null}),updateUser:async(args:unknown)=>{payload=args;return {error:null};},signOut:async()=>({error:null})}),secret,secret,'existing-password');assert.equal(payload.current_password,'existing-password');await assert.rejects(replacePassword(fake({}),secret,secret,''),/current password/);});

test('incorrect current credentials stop a password update even if provider enforcement is disabled',async()=>{let updated=false;await assert.rejects(replacePassword(fake({getUser:async()=>({data:{user:{id:'owner',email:'owner@example.com'}},error:null}),signInWithPassword:async()=>({data:{user:null},error:{code:'invalid_credentials'}}),updateUser:async()=>{updated=true;return {error:null};}}),secret,secret,'incorrect'),/current password is incorrect/);assert.equal(updated,false);});
